(include "src/reply.scm")
(include "src/encoding.scm")
(include "src/store-ctx.scm")
(include "src/shard.scm")
(include "src/commands/string.scm")
(include "src/commands/keys.scm")
(include "src/commands/set.scm")
(include "src/commands/zset.scm")
(include "test/harness.scm")
(include "test/set.scm")
(include "test/zset.scm")
(define H (store-open "/tmp/cc-setzset-db"))
(define ctx (make-ctx H))
(test-set ctx)
(test-zset ctx)
(store-close H)
(done!)
