(include "src/reply.scm")
(include "src/encoding.scm")
(include "src/store-ctx.scm")
(include "src/shard.scm")
(include "src/commands/string.scm")   ; for WRONGTYPE setup + dispatch
(include "src/commands/keys.scm")
(include "src/commands/hash.scm")
(include "src/commands/list.scm")
(include "test/harness.scm")
(include "test/hash.scm")
(include "test/list.scm")
(define H (store-open "/tmp/cc-hashlist-db"))
(define ctx (make-ctx H))
(test-hash ctx)
(test-list ctx)
(store-close H)
(done!)
